### ISSUE TITLE
Fix mirrors of Java and NodeJS for MacOS

### ISSUE THREAD

**Issue by alfeilex** [devonfw/ide-mirrors#22]
### Expected behavior

As a mac user, I want to setup devon ide

### Actual behavior

The mirrors of Java and NodeJS don't work as expected. The installation occurs an error.
### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1.  Setup devon-ide for Mac Mini (arch=arm64)

### Comments/Hints:
Maybe other urls are also affected

### Affected version:

* OS: Mac with **arm64** architecture

**Comment by alfeilex** [comment]
#23 PR is ready

**Comment by tobka777** [comment]
@alfeilex Can you check your changed mirrors for NodeJS and Java on Windows to see if the installation still works with the changed files. So just replace the mirrors for NodeJS and Java in the mirror folder and test.

**Comment by alfeilex** [comment]
@tobka777 I checked the changes and it works. But I had to change the git configuration because CRLF was set. Now it works. Maybe we should test the mirrors also on other Mac systems without arm64 architecture.

**Comment by hohwille** [comment]
Already done with PR #25 and #23
